<a href="https://colab.research.google.com/github/MaholeGn/Deep-Learning/blob/main/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **List in Python**

In [ ]:
list = ([5, 6 , 8 , 9],[5, 6 , 8 , 9])
list

([5, 6, 8, 9], [5, 6, 8, 9])

**Numpy Array**

In [ ]:
import numpy as np

np1 = np.random.rand(2,4)
np1

array([[0.7310297 , 0.69579209, 0.20714669, 0.73575374],
       [0.41281475, 0.59290983, 0.98453416, 0.39269916]])

In [ ]:
np1.dtype

dtype('float64')

**Tensor**

In [ ]:
import torch
tns2d = torch.randn(2 , 5)
tns2d

# tns2d.dtype


tensor([[-0.0647, -1.3738,  0.2603,  0.6499,  1.0443],
        [ 1.2217, -1.0042, -1.1842, -0.5640,  0.4113]])

In [ ]:
tns3d = torch.zeros(2,3,4)
tns3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])